import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

import { Path } from "@/shared/constants";

const publicDir = Path.Public;
const outputFile = Path.Assets;

const scanDir = (dir: string) => {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      files.push(...scanDir(fullPath));
    } else {
      files.push(fullPath);
    }
  }
  return files;
};

const files = scanDir(publicDir);
const lines = [
  "// Auto-generated by assets.ts script — do not edit manually",
  "// @ts-nocheck",
  "// biome-ignore-all lint: auto-generated file",
];
const entries: string[] = [];

for (let i = 0; i < files.length; i++) {
  const file = files[i];
  const importPath = relative("src/scripts", file).replace(/\\/g, "/");
  const urlPath = `/${relative(publicDir, file).replace(/\\/g, "/")}`;
  lines.push(`import _a${i} from "./${importPath}" with { type: "file" };`);
  entries.push(`\t"${urlPath}": _a${i}`);
}

lines.push("");
lines.push("export const staticAssets: Record<string, string> = {");
lines.push(entries.join(",\n") + (entries.length ? "," : ""));
lines.push("};");
lines.push("");

await Bun.write(outputFile, lines.join("\n"));
