import { rmSync, writeFileSync } from "node:fs";

rmSync("dist/public", { recursive: true, force: true });

const stub =
  "// Auto-generated by assets.ts script — do not edit manually\n" +
  "// @ts-nocheck\n" +
  "// biome-ignore-all lint: auto-generated file\n" +
  "export const staticAssets: Record<string, string> = {};\n";

writeFileSync("src/scripts/assets.generated.ts", stub);
